name: Remove old artifacts

on:
  schedule:
    # Every day at 1am
    - cron: '20 10 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '3 days'
        skip-recent: 10
